--
-- All SQL statements must be on a single line and end in a semicolon.
--

-- Dummy Data --
INSERT INTO dummy (created) VALUES (current_timestamp);

-- Populate Your Tables Here --
-- Users --
INSERT INTO people(email, pname, hash, avatar) VALUES ('averev@shareasale.com', 'Andy Vere', '$2b$10$BJPMsLIdVxqqZ7LTfnMZgujX16nr.X6pxos7o6mvi/gzMiBRW7.cW', 'https://www.shareicon.net/data/512x512/2016/07/26/802043_man_512x512.png');
INSERT INTO people(email, pname, hash, avatar) VALUES ('molly@books.com', 'mollymember', '$2b$10$3lBnHQWJzFE/0qUT/mdmtue7VY0DxUS7Q3M1VOdFVxE0ZCD4lIcfG', 'https://cdn1.iconfinder.com/data/icons/avatars-1-5/136/87-512.png');
INSERT INTO people(email, pname, hash, avatar) VALUES ('anna@books.com', 'annaadmin', '$2b$10$yIC933C4sytv/lbM4JVrYuP5n42TjIPMLan8nZoEe4Ugfi8wcA.ru', 'https://www.shareicon.net/data/512x512/2016/07/26/802031_user_512x512.png');

-- MAILS --
-- Molly inbox --
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember", "email":"molly@books.com"},"subject":"Sed vel enim sit amet nunc viverra dapibus.","body":"Sed vel enim sit amet nunc viverra dapibus.Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.", "received":"2022-11-27T09:38:47Z", "read":"False", "starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Quisque ut erat. Curabitur gravida nisi at nibh.","body":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","received":"2021-04-22T05:43:17Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin at turpis a pede posuere nonummy.","body":"Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","received":"2021-10-07T00:57:30Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","body":"Ut at dolor quis odio consequat varius. Integer ac leo.","received":"2021-09-18T02:30:57Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin eu mi.","body":"Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","received":"2021-12-17T12:46:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.","body":"Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.","received":"2022-10-29T17:00:28Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Vivamus vel nulla eget eros elementum pellentesque.","body":"Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.","received":"2021-09-25T12:48:22Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.","body":"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.","received":"2021-04-06T01:36:28Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Nullam varius. Nulla facilisi.","body":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","received":"2021-04-09T05:11:54Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.","received":"2022-10-26T03:54:31Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Etiam vel augue. Vestibulum rutrum rutrum neque.","body":"Vestibulum sed magna at nunc commodo placerat.","received":"2021-11-21T12:46:26Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","body":"Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","received":"2022-04-03T08:59:56Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","body":"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","received":"2021-02-07T11:06:07Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","received":"2021-08-24T21:46:52Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"In congue. Etiam justo.","body":"Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.","received":"2022-08-30T10:40:00Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","body":"Donec ut mauris eget massa tempor convallis.","received":"2021-06-19T22:34:17Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","body":"Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","received":"2021-03-06T23:53:44Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Nulla ut erat id mauris vulputate elementum.","body":"Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.","received":"2021-06-16T18:17:54Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","body":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","received":"2021-07-08T13:53:23Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Nulla ac enim.","body":"Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.","received":"2022-07-01T20:27:27Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin at turpis a pede posuere nonummy.","body":"Maecenas pulvinar lobortis est. Phasellus sit amet erat.","received":"2021-07-20T16:40:12Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","body":"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","received":"2022-01-06T04:16:55Z","read":"False","starred":"False"}');

-- Anna Inbox --
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Duis bibendum. Morbi non quam nec dui luctus rutrum.","body":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.","received":"2021-01-12T03:35:53Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Vivamus vel nulla eget eros elementum pellentesque.","body":"Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","received":"2022-12-01T10:45:11Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"In congue.","body":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.","received":"2022-12-02T01:49:02Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.","body":"Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.","received":"2021-09-07T02:14:37Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.","body":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2022-11-30T21:19:35Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Praesent blandit. Nam nulla.","body":"Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","received":"2022-11-29T16:59:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Morbi porttitor lorem id ligula.","body":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.","received":"2022-04-18T05:44:15Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"In congue.","body":"Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","received":"2022-05-27T10:27:12Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla tempus.","body":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.","received":"2021-04-20T11:36:59Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.","body":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2021-03-16T20:39:10Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla mollis molestie lorem.","body":"Morbi ut odio.","received":"2022-07-02T11:05:15Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"In blandit ultrices enim.","body":"Aliquam non mauris. Morbi non lectus.","received":"2022-08-14T13:06:21Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","body":"Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","received":"2021-04-02T00:00:54Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.","body":"Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.","received":"2021-07-31T09:23:47Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.","body":"Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","received":"2021-09-16T22:33:31Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Aenean auctor gravida sem.","body":"Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","received":"2021-07-18T08:31:34Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.","body":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.","received":"2022-05-31T08:36:01Z","read":"False","starred":"True"}');

-- Andy Inbox --
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.","body":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","received":"2022-05-11T05:55:22Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","body":"Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.","received":"2021-11-28T21:07:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Donec vitae nisi.","body":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.","received":"2022-04-17T14:05:53Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Sed accumsan felis. Ut at dolor quis odio consequat varius.","body":"Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.","received":"2021-07-05T15:14:44Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Pellentesque viverra pede ac diam.","body":"Duis bibendum.","received":"2021-02-05T05:19:44Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Phasellus sit amet erat. Nulla tempus.","body":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","received":"2021-08-24T03:27:40Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Pellentesque viverra pede ac diam.","body":"Maecenas pulvinar lobortis est.","received":"2022-08-10T18:01:09Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Nunc rhoncus dui vel sem.","body":"In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.","received":"2022-10-01T06:18:22Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Integer a nibh.","body":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","received":"2021-06-17T00:43:07Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.","body":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","received":"2019-08-16T06:00:41Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Morbi vel lectus in quam fringilla rhoncus.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","received":"2022-06-26T21:04:42Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","body":"Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.","received":"2022-01-13T21:14:10Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.","body":"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.","received":"2020-09-11T09:40:55Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","body":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","received":"2021-06-01T07:37:14Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Quisque porta volutpat erat.","body":"In hac habitasse platea dictumst.","received":"2019-12-08T22:42:10Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Maecenas tincidunt lacus at velit.","body":"Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","received":"2019-11-27T07:06:56Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","body":"Donec vitae nisi.","received":"2022-11-03T00:34:48Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Phasellus in felis.","body":"Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","received":"2022-10-13T05:12:30Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.","body":"Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","received":"2021-05-22T00:05:48Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Inbox', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","body":"Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2021-03-28T00:45:10Z","read":"True","starred":"False"}');

-- Molly Trash --
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember", "email":"molly@books.com"},"subject":"Sed vel enim sit amet nunc viverra dapibus.","body":"Sed vel enim sit amet nunc viverra dapibus.Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.", "received":"2022-11-27T09:38:47Z", "read":"False", "starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Quisque ut erat. Curabitur gravida nisi at nibh.","body":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","received":"2021-04-22T05:43:17Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin at turpis a pede posuere nonummy.","body":"Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","received":"2021-10-07T00:57:30Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","body":"Ut at dolor quis odio consequat varius. Integer ac leo.","received":"2021-09-18T02:30:57Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin eu mi.","body":"Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","received":"2021-12-17T12:46:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.","body":"Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.","received":"2022-10-29T17:00:28Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Vivamus vel nulla eget eros elementum pellentesque.","body":"Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.","received":"2021-09-25T12:48:22Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.","body":"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.","received":"2021-04-06T01:36:28Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Nullam varius. Nulla facilisi.","body":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","received":"2021-04-09T05:11:54Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.","received":"2022-10-26T03:54:31Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Etiam vel augue. Vestibulum rutrum rutrum neque.","body":"Vestibulum sed magna at nunc commodo placerat.","received":"2021-11-21T12:46:26Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","body":"Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","received":"2022-04-03T08:59:56Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","body":"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","received":"2021-02-07T11:06:07Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","received":"2021-08-24T21:46:52Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"In congue. Etiam justo.","body":"Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.","received":"2022-08-30T10:40:00Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","body":"Donec ut mauris eget massa tempor convallis.","received":"2021-06-19T22:34:17Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","body":"Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","received":"2021-03-06T23:53:44Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Nulla ut erat id mauris vulputate elementum.","body":"Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.","received":"2021-06-16T18:17:54Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","body":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","received":"2021-07-08T13:53:23Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Nulla ac enim.","body":"Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.","received":"2022-07-01T20:27:27Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","body":"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","received":"2022-01-06T04:16:55Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin at turpis a pede posuere nonummy.","body":"Maecenas pulvinar lobortis est. Phasellus sit amet erat.","received":"2021-07-20T16:40:12Z","read":"True","starred":"False"}');

-- Anna Trash --
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Duis bibendum. Morbi non quam nec dui luctus rutrum.","body":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.","received":"2021-01-12T03:35:53Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Vivamus vel nulla eget eros elementum pellentesque.","body":"Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","received":"2020-12-16T10:45:11Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"In congue.","body":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.","received":"2021-06-08T01:49:02Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.","body":"Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.","received":"2021-09-07T02:14:37Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.","body":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2022-06-01T21:19:35Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Praesent blandit. Nam nulla.","body":"Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","received":"2021-05-12T16:59:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Morbi porttitor lorem id ligula.","body":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.","received":"2022-04-18T05:44:15Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"In congue.","body":"Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","received":"2022-05-27T10:27:12Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla tempus.","body":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.","received":"2021-04-20T11:36:59Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.","body":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2021-03-16T20:39:10Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla mollis molestie lorem.","body":"Morbi ut odio.","received":"2022-07-02T11:05:15Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"In blandit ultrices enim.","body":"Aliquam non mauris. Morbi non lectus.","received":"2022-08-14T13:06:21Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","body":"Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","received":"2021-04-02T00:00:54Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.","body":"Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.","received":"2021-07-31T09:23:47Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.","body":"Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","received":"2021-09-16T22:33:31Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Aenean auctor gravida sem.","body":"Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","received":"2021-07-18T08:31:34Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"annaadmin","email":"anna@books.com"},"subject":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.","body":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.","received":"2022-05-31T08:36:01Z","read":"False","starred":"True"}');

-- Andy Trash --
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.","body":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","received":"2022-05-11T05:55:22Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","body":"Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.","received":"2021-11-28T21:07:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Donec vitae nisi.","body":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.","received":"2022-04-17T14:05:53Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Sed accumsan felis. Ut at dolor quis odio consequat varius.","body":"Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.","received":"2021-07-05T15:14:44Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Pellentesque viverra pede ac diam.","body":"Duis bibendum.","received":"2021-02-05T05:19:44Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Phasellus sit amet erat. Nulla tempus.","body":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","received":"2021-08-24T03:27:40Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Pellentesque viverra pede ac diam.","body":"Maecenas pulvinar lobortis est.","received":"2022-08-10T18:01:09Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Nunc rhoncus dui vel sem.","body":"In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.","received":"2022-10-01T06:18:22Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Integer a nibh.","body":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","received":"2021-06-17T00:43:07Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.","body":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","received":"2019-08-16T06:00:41Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Morbi vel lectus in quam fringilla rhoncus.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","received":"2022-06-26T21:04:42Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","body":"Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.","received":"2022-01-13T21:14:10Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.","body":"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.","received":"2020-09-11T09:40:55Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","body":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","received":"2021-06-01T07:37:14Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Quisque porta volutpat erat.","body":"In hac habitasse platea dictumst.","received":"2019-12-08T22:42:10Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Maecenas tincidunt lacus at velit.","body":"Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","received":"2019-11-27T07:06:56Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","body":"Donec vitae nisi.","received":"2022-11-03T00:34:48Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"annaadmin","email":"anna@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Phasellus in felis.","body":"Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","received":"2022-10-13T05:12:30Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.","body":"Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","received":"2021-05-22T00:05:48Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Trash', '{"from":{"name":"mollymember","email":"molly@books.com"},"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","body":"Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2021-03-28T00:45:10Z","read":"True","starred":"False"}');

-- Molly sent --
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember", "email":"molly@books.com"},"subject":"Sed vel enim sit amet nunc viverra dapibus.","body":"Sed vel enim sit amet nunc viverra dapibus.Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.", "received":"2022-11-27T09:38:47Z", "read":"False", "starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Quisque ut erat. Curabitur gravida nisi at nibh.","body":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","received":"2021-04-22T05:43:17Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin at turpis a pede posuere nonummy.","body":"Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","received":"2021-10-07T00:57:30Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","body":"Ut at dolor quis odio consequat varius. Integer ac leo.","received":"2021-09-18T02:30:57Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin eu mi.","body":"Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","received":"2021-12-17T12:46:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.","body":"Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.","received":"2022-10-29T17:00:28Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Vivamus vel nulla eget eros elementum pellentesque.","body":"Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.","received":"2021-09-25T12:48:22Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.","body":"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.","received":"2021-04-06T01:36:28Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Nullam varius. Nulla facilisi.","body":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","received":"2021-04-09T05:11:54Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.","received":"2022-10-26T03:54:31Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Etiam vel augue. Vestibulum rutrum rutrum neque.","body":"Vestibulum sed magna at nunc commodo placerat.","received":"2021-11-21T12:46:26Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","body":"Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","received":"2022-04-03T08:59:56Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","body":"Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","received":"2021-02-07T11:06:07Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","received":"2021-08-24T21:46:52Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"In congue. Etiam justo.","body":"Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.","received":"2022-08-30T10:40:00Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","body":"Donec ut mauris eget massa tempor convallis.","received":"2021-06-19T22:34:17Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","body":"Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.","received":"2021-03-06T23:53:44Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Nulla ut erat id mauris vulputate elementum.","body":"Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.","received":"2021-06-16T18:17:54Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","body":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","received":"2021-07-08T13:53:23Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Nulla ac enim.","body":"Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.","received":"2022-07-01T20:27:27Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Proin at turpis a pede posuere nonummy.","body":"Maecenas pulvinar lobortis est. Phasellus sit amet erat.","received":"2021-07-20T16:40:12Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"mollymember","email":"molly@books.com"},"subject":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","body":"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","received":"2022-01-06T04:16:55Z","read":"False","starred":"False"}');

-- Anna sent --
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Duis bibendum. Morbi non quam nec dui luctus rutrum.","body":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.","received":"2021-01-12T03:35:53Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Vivamus vel nulla eget eros elementum pellentesque.","body":"Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","received":"2020-12-16T10:45:11Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"In congue.","body":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.","received":"2021-06-08T01:49:02Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.","body":"Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.","received":"2021-09-07T02:14:37Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.","body":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2022-06-01T21:19:35Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Praesent blandit. Nam nulla.","body":"Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","received":"2021-05-12T16:59:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Morbi porttitor lorem id ligula.","body":"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.","received":"2022-04-18T05:44:15Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"In congue.","body":"Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","received":"2022-05-27T10:27:12Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla tempus.","body":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.","received":"2021-04-20T11:36:59Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.","body":"Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2021-03-16T20:39:10Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Nulla mollis molestie lorem.","body":"Morbi ut odio.","received":"2022-07-02T11:05:15Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"In blandit ultrices enim.","body":"Aliquam non mauris. Morbi non lectus.","received":"2022-08-14T13:06:21Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","body":"Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","received":"2021-04-02T00:00:54Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.","body":"Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.","received":"2021-07-31T09:23:47Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.","body":"Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","received":"2021-09-16T22:33:31Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"Andy Vere","email":"averev@shareasale.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Aenean auctor gravida sem.","body":"Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.","received":"2021-07-18T08:31:34Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"annaadmin","email":"anna@books.com"},"subject":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.","body":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.","received":"2022-05-31T08:36:01Z","read":"False","starred":"True"}');

-- Andy sent --
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.","body":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.","received":"2022-05-11T05:55:22Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","body":"Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.","received":"2021-11-28T21:07:21Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Donec vitae nisi.","body":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.","received":"2022-04-17T14:05:53Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Sed accumsan felis. Ut at dolor quis odio consequat varius.","body":"Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.","received":"2021-07-05T15:14:44Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Pellentesque viverra pede ac diam.","body":"Duis bibendum.","received":"2021-02-05T05:19:44Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Phasellus sit amet erat. Nulla tempus.","body":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","received":"2021-08-24T03:27:40Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Pellentesque viverra pede ac diam.","body":"Maecenas pulvinar lobortis est.","received":"2022-08-10T18:01:09Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Nunc rhoncus dui vel sem.","body":"In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.","received":"2022-10-01T06:18:22Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Integer a nibh.","body":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","received":"2021-06-17T00:43:07Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.","body":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","received":"2019-08-16T06:00:41Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Morbi vel lectus in quam fringilla rhoncus.","body":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","received":"2022-06-26T21:04:42Z","read":"True","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","body":"Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.","received":"2022-01-13T21:14:10Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.","body":"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.","received":"2020-09-11T09:40:55Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.","body":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","received":"2021-06-01T07:37:14Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Quisque porta volutpat erat.","body":"In hac habitasse platea dictumst.","received":"2019-12-08T22:42:10Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Maecenas tincidunt lacus at velit.","body":"Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","received":"2019-11-27T07:06:56Z","read":"True","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","body":"Donec vitae nisi.","received":"2022-11-03T00:34:48Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"annaadmin","email":"anna@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Phasellus in felis.","body":"Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","received":"2022-10-13T05:12:30Z","read":"False","starred":"False"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.","body":"Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","received":"2021-05-22T00:05:48Z","read":"False","starred":"True"}');
INSERT INTO mail(mailbox, mail) values ('Sent', '{"to":{"name":"mollymember","email":"molly@books.com"},"from":{"name":"Andy Vere","email":"averev@shareasale.com"},"subject":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.","body":"Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","received":"2021-03-28T00:45:10Z","read":"True","starred":"False"}');
